/drive_api:
  ros__parameters:
    drive_battery:
      cells: 2
      cell_voltage: 3.7  # V
    motor:
      # to_erpm is calculated
      # erpm_max is calculated
      back_emf: 3500
      poles: 4
      limit: 0
      pinion: 13
    differential:
      spur: 54
      pinion: 13
      ring: 37
    wheels:
      radius: 0.055  # m
    pwm:
      throttle:
        calm_value: 8959
        forward:
          min: 9159
          max: 11914
        backward:
          min: 8759
          max: 5980
      steering:
        calm_value: 9165
        left:
          min: 9072
          max: 8865
        right:
          min: 9465
          max: 11918
    angular_steering:
      left_max: 29.106255993  # deg
      right_max: 27.330086828  # deg
    run_mode: basic_vesc
/teensy_drive:
  ros__parameters:
    port: /dev/tty.teensy
/vesc:
  ros__parameters:
    port: /dev/tty.vesc
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 100.0
    current_min: 0.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 0.85
    servo_min: 0.15
    speed_max: 23250.0
    speed_min: -23250.0
